### ISSUE TITLE
InvalidArgumentException in Manager.php line 92: Driver [Linkedin] not supported.

### ISSUE THREAD

**Issue by li0nel** [SocialiteProviders/LinkedIn#1]
Hi there,

I followed all instructions on http://socialiteproviders.github.io/providers/linkedin/ but still can't get it working.

What is weird is that it successfully redirects me to LinkedIn with:
return \Socialize::with('linkedin')->scopes(['r_basicprofile','r_emailaddress'])->redirect();
It is the callback which fails:
\Socialize::with('Linkedin')->fields(array('id', 'email-address', 'first-name', 'last-name', 'positions', 'picture-urls::(original)'))->user();

Any help welcome!

**Comment by DraperStudio** [comment]
What is the exception that you get?

**Comment by li0nel** [comment]
InvalidArgumentException in vendor/laravel/framework/src/Illuminate/Support/Manager.php line 92: Driver [Linkedin] not supported

![screen shot 2015-03-05 at 10 26 35](https://cloud.githubusercontent.com/assets/7261684/6503186/7cbb39e0-c322-11e4-9a1d-2ed4e92625a4.png)

**Comment by DraperStudio** [comment]
Alright, you have a little typo here.

```php
\Socialize::with('Linkedin')->fields(array('id', 'email-address', 'first-name', 'last-name', 'positions', 'picture-urls::(original)'))->user();
```

You wrote **Linkedin** instead of lower-case **linkedin**.

**Comment by li0nel** [comment]
Thank you!
I will see how to extend /socialiteproviders/linkedin/src/Provider.php to be able to provide the fields.
Shouldn't I pass that as an argument to user() and forward to getUserByToken() where the url is forged?

How do you think is a good way to pass the scopes as a parameter as well?
Because my app needs r_basicprofile at some point and then r_fullprofile for other users.

Cheers

**Comment by DraperStudio** [comment]
All Socialite Providers only provide the id, nickname, name, email and avatar fields to keep a consistent format throughout all providers to prevent that you always need to look into the Provider.php to see how the User object you will get looks like. I think in most cases people just want the token and these few basic fields.

If you need to request other fields you could go two routes I guess. You could use the Provider like it is and use the access token you received to send another request to linkedin and get all fields without Socialite formatting them or you could overwrite the **getUserByToken** and **mapUserToObject** methods to fit your needs.

As for the scopes, shouldn't it be sufficient to just pass in the scopes like that?

```php
// When you need basic_profile
return \Socialize::with('linkedin')->scopes(['r_basicprofile'])->redirect();

// When you need full_profile
return \Socialize::with('linkedin')->scopes(['r_fullprofile'])->redirect();
```
