### ISSUE TITLE
Cannot access protected property Laravel\Socialite\Two\User::$user

### ISSUE THREAD

**Issue by stgalkin** [SocialiteProviders/LinkedIn#11]
Hi. I got the error at production `Cannot access protected property Laravel\Socialite\Two\User::$user.` 
The data array contains user which protected and i can't get the name or email by $user->user['emailAddress'] or $user->user->getEmail() or $user->getEmail(). At the homestead everything is ok but then i add productioon url to linkedIn APP i got this error.
[pic.1](https://gyazo.com/fc7f8b046d4fba508c7b786b16cc5553)
[pic.2](https://gyazo.com/b6feeaba94408e7af5292540730b4edb)

**Comment by AndyWendt** [comment]
@stgalkin I think you may want to use either `$user['emailAddress']` to retrieve a single entity.  Or use `$user->getRaw()` to retrieve the raw user object.  

Socialites AbstractUser class implements array access and also uses the getRaw() method to return the raw user: https://github.com/laravel/socialite/blob/f3e3bdf9368b96b82635cb88ab02944b7d036669/src/AbstractUser.php
