### ISSUE TITLE
Content encoding error

### ISSUE THREAD

**Issue by CJLees01** [SocialiteProviders/LinkedIn#3]
I'm having problems with the re-direct to LinkedIn - the URL looks to be constructed correctly...

https://www.linkedin.com/uas/oauth2/authorization?client_id=[REMOVED]&redirect_uri=http%3A%2F%2Ftest.dev%2Flinkedin%2Freply&scope=r_basicprofile%2Cr_emailaddress&state=ee804772a4c23208ed356f5b7ef51ec3e73d0500&response_type=code

... but my browser (Firefox) returns with a content encoding error and mentions invalid/unsupported form of compression ??

![error](https://cloud.githubusercontent.com/assets/4609788/7822912/8d2a366e-03f0-11e5-9804-3bbd6f337fc0.png)

What am I doing wrong?

**Comment by DraperStudio** [comment]
Did you try the decoed url? Meaning no escaping etc.

I once faced that issue with LinkedIn because it seems they wanna see a normal character and not %2c and things like that.

**Comment by CJLees01** [comment]
Thanks for the speedy response. 
It appears to not make any difference I'm afraid, the following URL still returns the same error.

https://www.linkedin.com/uas/oauth2/authorization?client_id=[REOMVED]&redirect_uri=http://test.dev/auth/linkedin/reply&scope=r_basicprofile,r_emailaddress&state=5c6c274546b53233339158d0163f26b4077cc832&response_type=code

**Comment by CJLees01** [comment]
Reading a few similar stackoverflow issues, it seems that the issue may be related to the HTTP request headers being set. 

By default, Firefox (and I'm guessing many other browsers) accept gzip. If I change the Firefox configs (about:config in URL) and delete the default *network.http.accept-encoding* value, then I get the page loads even with the encoded characters.

Is there any way to explicitly set HTTP headers for this request so users don't need to change their configs?

**Comment by DraperStudio** [comment]
Just from my mind right now I don't know any way to set http headers for a redirect but I will look into the issue during todays noon or evening and hope I am able to tell you more after that.

**Comment by DraperStudio** [comment]
I had a quick look into it yesterday evening but didn't found a nice solution for that issue. I will take a closer look during the weekend.

**Comment by CJLees01** [comment]
Thanks - I really appreciate your help here. I really want to stick with Socialite if I can!

**Comment by DraperStudio** [comment]
Sorry for getting back that late. Sadly I haven't found a solution for it yet.

Does this issue only occur in Firefox? Had no issues in Chrome and Safari.

**Comment by CJLees01** [comment]
:blush: Comparing the URL call from an old Laravel 4 OAuth package with yours, I finally tracked down that I mixed my client_id and client_secret configs. It's a pretty stupid response back from LinkedIn when a client_id is wrong, but there you go...

I'm really sorry to have wasted your time with such a stupid error on my part. Thanks

**Comment by AndyWendt** [comment]
lol.  I was trying to figure this out.  wow

That's awesome.  I'm glad it's working!
