### ISSUE TITLE
InvalidStateException

### ISSUE THREAD

**Issue by li0nel** [SocialiteProviders/LinkedIn#6]
From time to time, Socialite::driver('linkedin')->user(); will fire an InvalidStateException.

I can't reproduce it though.

Do you think it comes from LinkedIn API or the Socialite driver?

**Comment by DraperStudio** [comment]
This comes from the LinkedIn API.

**Comment by felipemarques** [comment]
@li0nel try use Socialite::with('linkedin')->user() ...
